name: Copy Latest File to README

on:
  push:
    branches:
      - main

jobs:
  copy-latest-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find latest file
      id: find-latest
      run: |
        latest_file=$(ls -t weekly-notes | head -n1)
        echo "::set-output name=latest_file::$latest_file"

    - name: Copy latest file to README
      run: |
        cp weekly-notes/${{ steps.find-latest.outputs.latest_file }} README.md

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with latest Weekly Note"
        git push
