name: Copy Latest File to README

on:
  push:
    branches:
      - main

jobs:
  copy-latest-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find latest file
      id: find-latest
      run: |
        latest_file=$(ls -t path/to/your/directory | head -n1)
        echo "::set-output name=latest_file::$latest_file"

    - name: Copy latest file to README
      run: |
        cp path/to/your/directory/${{ steps.find-latest.outputs.latest_file }} README.md

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Update README with latest file"

    - name: Push changes
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          fs.writeFileSync('README.md', fs.readFileSync('README.md', 'utf-8'));
